CHARACTER_MAP = [
    # 0b00000000:
    [
         [False, False, False, True, False],
         [False, False, True, False, True],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, False, False, False],
    ],
    # 0b00000001:
    [
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [True, False, True, False, False],
         [False, True, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b00000010:
    [
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, True, False, True, False],
         [True, False, True, False, True],
         [True, False, True, False, True],
         [False, True, False, True, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b00000011:
    [
         [True, True, True, True, True],
         [True, False, False, False, True],
         [True, False, False, True, False],
         [True, False, True, False, False],
         [True, True, False, False, False],
         [True, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b00000100:
    [
         [False, False, False, False, True],
         [False, False, False, False, True],
         [False, False, True, False, True],
         [False, True, False, False, True],
         [True, True, True, True, True],
         [False, True, False, False, False],
         [False, False, True, False, False],
         [False, False, False, False, False],
    ],
    # 0b00000101:
    [
         [False, False, True, False, False],
         [False, True, True, True, False],
         [True, False, True, False, True],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, False, False, False],
    ],
    # 0b00000110:
    [
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [True, False, True, False, True],
         [False, True, True, True, False],
         [False, False, True, False, False],
         [False, False, False, False, False],
    ],
    # 0b00000111:
    [
         [False, False, False, False, False],
         [False, False, True, False, False],
         [False, False, False, True, False],
         [True, True, True, True, True],
         [False, False, False, True, False],
         [False, False, True, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b00001000:
    [
         [False, False, False, False, False],
         [False, False, True, False, False],
         [False, True, False, False, False],
         [True, True, True, True, True],
         [False, True, False, False, False],
         [False, False, True, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b00001001:
    [
         [True, True, True, True, True],
         [True, False, False, False, False],
         [True, False, False, False, False],
         [True, False, False, False, False],
         [True, False, False, False, False],
         [True, False, False, False, False],
         [True, False, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b00001010:
    [
         [True, True, True, True, True],
         [False, False, False, False, True],
         [False, False, False, False, True],
         [False, False, False, False, True],
         [False, False, False, False, True],
         [False, False, False, False, True],
         [False, False, False, False, True],
         [False, False, False, False, False],
    ],
    # 0b00001011:
    [
         [True, False, False, False, False],
         [True, False, False, False, False],
         [True, False, False, False, False],
         [True, False, False, False, False],
         [True, False, False, False, False],
         [True, False, False, False, False],
         [True, True, True, True, True],
         [False, False, False, False, False],
    ],
    # 0b00001100:
    [
         [False, False, False, False, True],
         [False, False, False, False, True],
         [False, False, False, False, True],
         [False, False, False, False, True],
         [False, False, False, False, True],
         [False, False, False, False, True],
         [True, True, True, True, True],
         [False, False, False, False, False],
    ],
    # 0b00001101:
    [
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, True, True, False, False],
         [False, True, True, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b00001110:
    [
         [False, True, True, True, False],
         [True, False, False, True, True],
         [True, False, True, False, True],
         [True, False, False, True, True],
         [True, False, True, False, True],
         [True, False, True, False, True],
         [False, True, True, True, False],
         [False, False, False, False, False],
    ],
    # 0b00001111:
    [
         [False, True, True, True, False],
         [True, True, False, True, True],
         [True, False, True, False, True],
         [True, False, True, True, True],
         [True, False, True, False, True],
         [True, True, False, True, True],
         [False, True, True, True, False],
         [False, False, False, False, False],
    ],
    # 0b00010000:
    [
         [True, True, True, True, True],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [True, False, False, False, True],
         [True, True, False, True, True],
         [True, False, True, False, True],
         [True, False, False, False, True],
         [False, False, False, False, False],
    ],
    # 0b00010001:
    [
         [False, False, True, False, False],
         [False, False, True, False, False],
         [True, True, True, True, True],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, False, False, False],
    ],
    # 0b00010010:
    [
         [False, True, True, True, False],
         [True, False, False, False, False],
         [False, True, True, True, False],
         [True, False, False, False, True],
         [False, True, True, True, False],
         [False, False, False, False, True],
         [False, True, True, True, False],
         [False, False, False, False, False],
    ],
    # 0b00010011:
    [
         [False, True, True, True, True],
         [True, True, True, False, True],
         [True, True, True, False, True],
         [False, True, True, False, True],
         [False, False, True, False, True],
         [False, False, True, False, True],
         [False, False, True, False, True],
         [False, False, False, False, False],
    ],
    # 0b00010100:
    [
         [True, True, True, True, True],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [True, False, False, False, False],
         [True, False, False, False, False],
         [True, False, False, False, False],
         [True, False, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b00010101:
    [
         [False, False, False, False, False],
         [False, False, False, False, True],
         [False, False, False, True, True],
         [False, False, True, False, True],
         [False, True, False, False, True],
         [True, False, False, False, True],
         [True, True, True, True, True],
         [False, False, False, False, False],
    ],
    # 0b00010110:
    [
         [False, True, True, True, False],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [True, True, True, True, True],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [False, True, True, True, False],
         [False, False, False, False, False],
    ],
    # 0b00010111:
    [
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, True, False, True, False],
         [False, True, False, True, False],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [False, False, False, False, False],
    ],
    # 0b00011000:
    [
         [True, True, True, True, True],
         [True, False, False, False, True],
         [False, False, False, False, False],
         [False, True, True, True, False],
         [False, False, False, False, False],
         [True, False, False, False, True],
         [True, True, True, True, True],
         [False, False, False, False, False],
    ],
    # 0b00011001:
    [
         [True, True, True, True, True],
         [False, True, False, True, False],
         [False, True, False, True, False],
         [False, True, False, True, False],
         [False, True, False, True, False],
         [False, True, False, True, False],
         [False, True, False, True, False],
         [False, False, False, False, False],
    ],
    # 0b00011010:
    [
         [True, True, True, True, True],
         [False, True, False, False, False],
         [False, False, True, False, False],
         [False, False, False, True, False],
         [False, False, True, False, False],
         [False, True, False, False, False],
         [True, True, True, True, True],
         [False, False, False, False, False],
    ],
    # 0b00011011:
    [
         [False, True, False, True, False],
         [True, False, True, False, True],
         [True, False, True, False, True],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, False, False, False],
    ],
    # 0b00011100:
    [
         [False, True, True, True, False],
         [False, False, True, False, False],
         [False, True, True, True, False],
         [True, False, True, False, True],
         [True, False, True, False, True],
         [False, True, True, True, False],
         [False, False, True, False, False],
         [False, True, True, True, False],
    ],
    # 0b00011101:
    [
         [True, False, True, False, True],
         [True, False, True, False, True],
         [True, False, True, False, True],
         [True, False, True, False, True],
         [False, True, True, True, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, False, False, False],
    ],
    # 0b00011110:
    [
         [False, True, True, True, False],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [False, True, False, True, False],
         [False, True, False, True, False],
         [True, True, False, True, True],
         [False, False, False, False, False],
    ],
    # 0b00011111:
    [
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, True, True, False, True],
         [True, False, False, True, False],
         [True, False, False, True, False],
         [True, False, False, True, False],
         [False, True, True, False, True],
         [False, False, False, False, False],
    ],
    # 0b00100000:
    [
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b00100001:
    [
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, True, False, False],
         [False, False, False, False, False],
    ],
    # 0b00100010:
    [
         [False, True, False, True, False],
         [False, True, False, True, False],
         [False, True, False, True, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b00100011:
    [
         [False, True, False, True, False],
         [False, True, False, True, False],
         [True, True, True, True, True],
         [False, True, False, True, False],
         [True, True, True, True, True],
         [False, True, False, True, False],
         [False, True, False, True, False],
         [False, False, False, False, False],
    ],
    # 0b00100100:
    [
         [False, False, True, False, False],
         [False, True, True, True, True],
         [True, False, True, False, False],
         [False, True, True, True, False],
         [False, False, True, False, True],
         [True, True, True, True, False],
         [False, False, True, False, False],
         [False, False, False, False, False],
    ],
    # 0b00100101:
    [
         [True, True, False, False, False],
         [True, True, False, False, True],
         [False, False, False, True, False],
         [False, False, True, False, False],
         [False, True, False, False, False],
         [True, False, False, True, True],
         [False, False, False, True, True],
         [False, False, False, False, False],
    ],
    # 0b00100110:
    [
         [False, True, True, False, False],
         [True, False, False, True, False],
         [True, False, True, False, False],
         [False, True, False, False, False],
         [True, False, True, False, True],
         [True, False, False, True, False],
         [False, True, True, False, True],
         [False, False, False, False, False],
    ],
    # 0b00100111:
    [
         [False, True, True, False, False],
         [False, False, True, False, False],
         [False, True, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b00101000:
    [
         [False, False, False, True, False],
         [False, False, True, False, False],
         [False, True, False, False, False],
         [False, True, False, False, False],
         [False, True, False, False, False],
         [False, False, True, False, False],
         [False, False, False, True, False],
         [False, False, False, False, False],
    ],
    # 0b00101001:
    [
         [False, True, False, False, False],
         [False, False, True, False, False],
         [False, False, False, True, False],
         [False, False, False, True, False],
         [False, False, False, True, False],
         [False, False, True, False, False],
         [False, True, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b00101010:
    [
         [False, False, False, False, False],
         [False, False, True, False, False],
         [True, False, True, False, True],
         [False, True, True, True, False],
         [True, False, True, False, True],
         [False, False, True, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b00101011:
    [
         [False, False, False, False, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [True, True, True, True, True],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b00101100:
    [
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, True, True, False, False],
         [False, False, True, False, False],
         [False, True, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b00101101:
    [
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [True, True, True, True, True],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b00101110:
    [
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, True, True, False, False],
         [False, True, True, False, False],
         [False, False, False, False, False],
    ],
    # 0b00101111:
    [
         [False, False, False, False, False],
         [False, False, False, False, True],
         [False, False, False, True, False],
         [False, False, True, False, False],
         [False, True, False, False, False],
         [True, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b00110000:
    [
         [False, True, True, True, False],
         [True, False, False, False, True],
         [True, False, False, True, True],
         [True, False, True, False, True],
         [True, True, False, False, True],
         [True, False, False, False, True],
         [False, True, True, True, False],
         [False, False, False, False, False],
    ],
    # 0b00110001:
    [
         [False, False, True, False, False],
         [False, True, True, False, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, True, True, True, False],
         [False, False, False, False, False],
    ],
    # 0b00110010:
    [
         [False, True, True, True, False],
         [True, False, False, False, True],
         [False, False, False, False, True],
         [False, False, False, True, False],
         [False, False, True, False, False],
         [False, True, False, False, False],
         [True, True, True, True, True],
         [False, False, False, False, False],
    ],
    # 0b00110011:
    [
         [True, True, True, True, True],
         [False, False, False, True, False],
         [False, False, True, False, False],
         [False, False, False, True, False],
         [False, False, False, False, True],
         [True, False, False, False, True],
         [False, True, True, True, False],
         [False, False, False, False, False],
    ],
    # 0b00110100:
    [
         [False, False, False, True, False],
         [False, False, True, True, False],
         [False, True, False, True, False],
         [True, False, False, True, False],
         [True, True, True, True, True],
         [False, False, False, True, False],
         [False, False, False, True, False],
         [False, False, False, False, False],
    ],
    # 0b00110101:
    [
         [True, True, True, True, True],
         [True, False, False, False, False],
         [True, True, True, True, False],
         [False, False, False, False, True],
         [False, False, False, False, True],
         [True, False, False, False, True],
         [False, True, True, True, False],
         [False, False, False, False, False],
    ],
    # 0b00110110:
    [
         [False, False, True, True, False],
         [False, True, False, False, False],
         [True, False, False, False, False],
         [True, True, True, True, False],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [False, True, True, True, False],
         [False, False, False, False, False],
    ],
    # 0b00110111:
    [
         [True, True, True, True, True],
         [False, False, False, False, True],
         [False, False, False, True, False],
         [False, False, True, False, False],
         [False, True, False, False, False],
         [False, True, False, False, False],
         [False, True, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b00111000:
    [
         [False, True, True, True, False],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [False, True, True, True, False],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [False, True, True, True, False],
         [False, False, False, False, False],
    ],
    # 0b00111001:
    [
         [False, True, True, True, False],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [False, True, True, True, True],
         [False, False, False, False, True],
         [False, False, False, True, False],
         [False, True, True, False, False],
         [False, False, False, False, False],
    ],
    # 0b00111010:
    [
         [False, False, False, False, False],
         [False, True, True, False, False],
         [False, True, True, False, False],
         [False, False, False, False, False],
         [False, True, True, False, False],
         [False, True, True, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b00111011:
    [
         [False, False, False, False, False],
         [False, True, True, False, False],
         [False, True, True, False, False],
         [False, False, False, False, False],
         [False, True, True, False, False],
         [False, False, True, False, False],
         [False, True, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b00111100:
    [
         [False, False, False, True, False],
         [False, False, True, False, False],
         [False, True, False, False, False],
         [True, False, False, False, False],
         [False, True, False, False, False],
         [False, False, True, False, False],
         [False, False, False, True, False],
         [False, False, False, False, False],
    ],
    # 0b00111101:
    [
         [False, False, False, False, False],
         [False, False, False, False, False],
         [True, True, True, True, True],
         [False, False, False, False, False],
         [True, True, True, True, True],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b00111110:
    [
         [False, True, False, False, False],
         [False, False, True, False, False],
         [False, False, False, True, False],
         [False, False, False, False, True],
         [False, False, False, True, False],
         [False, False, True, False, False],
         [False, True, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b00111111:
    [
         [False, True, True, True, False],
         [True, False, False, False, True],
         [False, False, False, False, True],
         [False, False, False, True, False],
         [False, False, True, False, False],
         [False, False, False, False, False],
         [False, False, True, False, False],
         [False, False, False, False, False],
    ],
    # 0b01000000:
    [
         [False, True, True, True, False],
         [True, False, False, False, True],
         [False, False, False, False, True],
         [False, True, True, False, True],
         [True, False, True, False, True],
         [True, False, True, False, True],
         [False, True, True, True, False],
         [False, False, False, False, False],
    ],
    # 0b01000001:
    [
         [False, True, True, True, False],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [True, True, True, True, True],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [False, False, False, False, False],
    ],
    # 0b01000010:
    [
         [True, True, True, True, False],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [True, True, True, True, False],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [True, True, True, True, False],
         [False, False, False, False, False],
    ],
    # 0b01000011:
    [
         [False, True, True, True, False],
         [True, False, False, False, True],
         [True, False, False, False, False],
         [True, False, False, False, False],
         [True, False, False, False, False],
         [True, False, False, False, True],
         [False, True, True, True, False],
         [False, False, False, False, False],
    ],
    # 0b01000100:
    [
         [True, True, True, False, False],
         [True, False, False, True, False],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [True, False, False, True, False],
         [True, True, True, False, False],
         [False, False, False, False, False],
    ],
    # 0b01000101:
    [
         [True, True, True, True, True],
         [True, False, False, False, False],
         [True, False, False, False, False],
         [True, True, True, True, False],
         [True, False, False, False, False],
         [True, False, False, False, False],
         [True, True, True, True, True],
         [False, False, False, False, False],
    ],
    # 0b01000110:
    [
         [True, True, True, True, True],
         [True, False, False, False, False],
         [True, False, False, False, False],
         [True, True, True, True, False],
         [True, False, False, False, False],
         [True, False, False, False, False],
         [True, False, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b01000111:
    [
         [False, True, True, True, False],
         [True, False, False, False, True],
         [True, False, False, False, False],
         [True, False, True, True, True],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [False, True, True, True, True],
         [False, False, False, False, False],
    ],
    # 0b01001000:
    [
         [True, False, False, False, True],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [True, True, True, True, True],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [False, False, False, False, False],
    ],
    # 0b01001001:
    [
         [False, True, True, True, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, True, True, True, False],
         [False, False, False, False, False],
    ],
    # 0b01001010:
    [
         [False, False, True, True, True],
         [False, False, False, True, False],
         [False, False, False, True, False],
         [False, False, False, True, False],
         [False, False, False, True, False],
         [True, False, False, True, False],
         [False, True, True, False, False],
         [False, False, False, False, False],
    ],
    # 0b01001011:
    [
         [True, False, False, False, True],
         [True, False, False, True, False],
         [True, False, True, False, False],
         [True, True, False, False, False],
         [True, False, True, False, False],
         [True, False, False, True, False],
         [True, False, False, False, True],
         [False, False, False, False, False],
    ],
    # 0b01001100:
    [
         [True, False, False, False, False],
         [True, False, False, False, False],
         [True, False, False, False, False],
         [True, False, False, False, False],
         [True, False, False, False, False],
         [True, False, False, False, False],
         [True, True, True, True, True],
         [False, False, False, False, False],
    ],
    # 0b01001101:
    [
         [True, False, False, False, True],
         [True, True, False, True, True],
         [True, False, True, False, True],
         [True, False, True, False, True],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [False, False, False, False, False],
    ],
    # 0b01001110:
    [
         [True, False, False, False, True],
         [True, False, False, False, True],
         [True, True, False, False, True],
         [True, False, True, False, True],
         [True, False, False, True, True],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [False, False, False, False, False],
    ],
    # 0b01001111:
    [
         [False, True, True, True, False],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [False, True, True, True, False],
         [False, False, False, False, False],
    ],
    # 0b01010000:
    [
         [True, True, True, True, False],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [True, True, True, True, False],
         [True, False, False, False, False],
         [True, False, False, False, False],
         [True, False, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b01010001:
    [
         [False, True, True, True, False],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [True, False, True, False, True],
         [True, False, False, True, False],
         [False, True, True, False, True],
         [False, False, False, False, False],
    ],
    # 0b01010010:
    [
         [True, True, True, True, False],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [True, True, True, True, False],
         [True, False, True, False, False],
         [True, False, False, True, False],
         [True, False, False, False, True],
         [False, False, False, False, False],
    ],
    # 0b01010011:
    [
         [False, True, True, True, True],
         [True, False, False, False, False],
         [True, False, False, False, False],
         [False, True, True, True, False],
         [False, False, False, False, True],
         [False, False, False, False, True],
         [True, True, True, True, False],
         [False, False, False, False, False],
    ],
    # 0b01010100:
    [
         [True, True, True, True, True],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, False, False, False],
    ],
    # 0b01010101:
    [
         [True, False, False, False, True],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [False, True, True, True, False],
         [False, False, False, False, False],
    ],
    # 0b01010110:
    [
         [True, False, False, False, True],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [False, True, False, True, False],
         [False, False, True, False, False],
         [False, False, False, False, False],
    ],
    # 0b01010111:
    [
         [True, False, False, False, True],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [True, False, True, False, True],
         [True, False, True, False, True],
         [True, False, True, False, True],
         [False, True, False, True, False],
         [False, False, False, False, False],
    ],
    # 0b01011000:
    [
         [True, False, False, False, True],
         [True, False, False, False, True],
         [False, True, False, True, False],
         [False, False, True, False, False],
         [False, True, False, True, False],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [False, False, False, False, False],
    ],
    # 0b01011001:
    [
         [True, False, False, False, True],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [False, True, False, True, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, False, False, False],
    ],
    # 0b01011010:
    [
         [True, True, True, True, True],
         [False, False, False, False, True],
         [False, False, False, True, False],
         [False, False, True, False, False],
         [False, True, False, False, False],
         [True, False, False, False, False],
         [True, True, True, True, True],
         [False, False, False, False, False],
    ],
    # 0b01011011:
    [
         [False, True, True, True, False],
         [False, True, False, False, False],
         [False, True, False, False, False],
         [False, True, False, False, False],
         [False, True, False, False, False],
         [False, True, False, False, False],
         [False, True, True, True, False],
         [False, False, False, False, False],
    ],
    # 0b01011100:
    [
         [True, False, False, False, True],
         [False, True, False, True, False],
         [True, True, True, True, True],
         [False, False, True, False, False],
         [True, True, True, True, True],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, False, False, False],
    ],
    # 0b01011101:
    [
         [False, True, True, True, False],
         [False, False, False, True, False],
         [False, False, False, True, False],
         [False, False, False, True, False],
         [False, False, False, True, False],
         [False, False, False, True, False],
         [False, True, True, True, False],
         [False, False, False, False, False],
    ],
    # 0b01011110:
    [
         [False, False, True, False, False],
         [False, True, False, True, False],
         [True, False, False, False, True],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b01011111:
    [
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [True, True, True, True, True],
         [False, False, False, False, False],
    ],
    # 0b01100000:
    [
         [False, True, False, False, False],
         [False, False, True, False, False],
         [False, False, False, True, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b01100001:
    [
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, True, True, True, False],
         [False, False, False, False, True],
         [False, True, True, True, True],
         [True, False, False, False, True],
         [False, True, True, True, True],
         [False, False, False, False, False],
    ],
    # 0b01100010:
    [
         [True, False, False, False, False],
         [True, False, False, False, False],
         [True, False, True, True, False],
         [True, True, False, False, True],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [True, True, True, True, False],
         [False, False, False, False, False],
    ],
    # 0b01100011:
    [
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, True, True, True, False],
         [True, False, False, False, False],
         [True, False, False, False, False],
         [True, False, False, False, True],
         [False, True, True, True, False],
         [False, False, False, False, False],
    ],
    # 0b01100100:
    [
         [False, False, False, False, True],
         [False, False, False, False, True],
         [False, True, True, False, True],
         [True, False, False, True, True],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [False, True, True, True, True],
         [False, False, False, False, False],
    ],
    # 0b01100101:
    [
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, True, True, True, False],
         [True, False, False, False, True],
         [True, True, True, True, True],
         [True, False, False, False, False],
         [False, True, True, True, False],
         [False, False, False, False, False],
    ],
    # 0b01100110:
    [
         [False, False, True, True, False],
         [False, True, False, False, True],
         [False, True, False, False, False],
         [True, True, True, False, False],
         [False, True, False, False, False],
         [False, True, False, False, False],
         [False, True, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b01100111:
    [
         [False, False, False, False, False],
         [False, True, True, True, True],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [False, True, True, True, True],
         [False, False, False, False, True],
         [False, True, True, True, False],
         [False, False, False, False, False],
    ],
    # 0b01101000:
    [
         [True, False, False, False, False],
         [True, False, False, False, False],
         [True, False, True, True, False],
         [True, True, False, False, True],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [False, False, False, False, False],
    ],
    # 0b01101001:
    [
         [False, False, True, False, False],
         [False, False, False, False, False],
         [False, True, True, False, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, True, True, True, False],
         [False, False, False, False, False],
    ],
    # 0b01101010:
    [
         [False, False, False, True, False],
         [False, False, False, False, False],
         [False, False, True, True, False],
         [False, False, False, True, False],
         [False, False, False, True, False],
         [True, False, False, True, False],
         [False, True, True, False, False],
         [False, False, False, False, False],
    ],
    # 0b01101011:
    [
         [True, False, False, False, False],
         [True, False, False, False, False],
         [True, False, False, True, False],
         [True, False, True, False, False],
         [True, True, False, False, False],
         [True, False, True, False, False],
         [True, False, False, True, False],
         [False, False, False, False, False],
    ],
    # 0b01101100:
    [
         [False, True, True, False, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, True, True, True, False],
         [False, False, False, False, False],
    ],
    # 0b01101101:
    [
         [False, False, False, False, False],
         [False, False, False, False, False],
         [True, True, False, True, False],
         [True, False, True, False, True],
         [True, False, True, False, True],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [False, False, False, False, False],
    ],
    # 0b01101110:
    [
         [False, False, False, False, False],
         [False, False, False, False, False],
         [True, False, True, True, False],
         [True, True, False, False, True],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [False, False, False, False, False],
    ],
    # 0b01101111:
    [
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, True, True, True, False],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [False, True, True, True, False],
         [False, False, False, False, False],
    ],
    # 0b01110000:
    [
         [False, False, False, False, False],
         [False, False, False, False, False],
         [True, True, True, True, False],
         [True, False, False, False, True],
         [True, True, True, True, False],
         [True, False, False, False, False],
         [True, False, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b01110001:
    [
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, True, True, False, True],
         [True, False, False, True, True],
         [False, True, True, True, True],
         [False, False, False, False, True],
         [False, False, False, False, True],
         [False, False, False, False, False],
    ],
    # 0b01110010:
    [
         [False, False, False, False, False],
         [False, False, False, False, False],
         [True, False, True, True, False],
         [True, True, False, False, True],
         [True, False, False, False, False],
         [True, False, False, False, False],
         [True, False, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b01110011:
    [
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, True, True, True, False],
         [True, False, False, False, False],
         [False, True, True, True, False],
         [False, False, False, False, True],
         [True, True, True, True, False],
         [False, False, False, False, False],
    ],
    # 0b01110100:
    [
         [False, True, False, False, False],
         [False, True, False, False, False],
         [True, True, True, False, False],
         [False, True, False, False, False],
         [False, True, False, False, False],
         [False, True, False, False, True],
         [False, False, True, True, False],
         [False, False, False, False, False],
    ],
    # 0b01110101:
    [
         [False, False, False, False, False],
         [False, False, False, False, False],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [True, False, False, True, True],
         [False, True, True, False, True],
         [False, False, False, False, False],
    ],
    # 0b01110110:
    [
         [False, False, False, False, False],
         [False, False, False, False, False],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [False, True, False, True, False],
         [False, False, True, False, False],
         [False, False, False, False, False],
    ],
    # 0b01110111:
    [
         [False, False, False, False, False],
         [False, False, False, False, False],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [True, False, True, False, True],
         [True, False, True, False, True],
         [False, True, False, True, False],
         [False, False, False, False, False],
    ],
    # 0b01111000:
    [
         [False, False, False, False, False],
         [False, False, False, False, False],
         [True, False, False, False, True],
         [False, True, False, True, False],
         [False, False, True, False, False],
         [False, True, False, True, False],
         [True, False, False, False, True],
         [False, False, False, False, False],
    ],
    # 0b01111001:
    [
         [False, False, False, False, False],
         [False, False, False, False, False],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [False, True, True, True, True],
         [False, False, False, False, True],
         [False, True, True, True, False],
         [False, False, False, False, False],
    ],
    # 0b01111010:
    [
         [False, False, False, False, False],
         [False, False, False, False, False],
         [True, True, True, True, True],
         [False, False, False, True, False],
         [False, False, True, False, False],
         [False, True, False, False, False],
         [True, True, True, True, True],
         [False, False, False, False, False],
    ],
    # 0b01111011:
    [
         [False, False, False, True, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, True, False, False, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, False, True, False],
         [False, False, False, False, False],
    ],
    # 0b01111100:
    [
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, False, False, False],
    ],
    # 0b01111101:
    [
         [False, True, False, False, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, False, True, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, True, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b01111110:
    [
         [False, False, False, False, False],
         [False, False, True, False, False],
         [False, False, False, True, False],
         [True, True, True, True, True],
         [False, False, False, True, False],
         [False, False, True, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b01111111:
    [
         [False, False, False, False, False],
         [False, False, True, False, False],
         [False, True, False, False, False],
         [True, True, True, True, True],
         [False, True, False, False, False],
         [False, False, True, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b10000000:
    [
         [False, True, True, True, True],
         [True, False, False, False, False],
         [True, False, False, False, False],
         [True, False, False, False, False],
         [False, True, True, True, True],
         [False, False, False, True, False],
         [False, True, True, True, False],
         [False, False, False, False, False],
    ],
    # 0b10000001:
    [
         [False, False, False, False, False],
         [False, True, False, True, False],
         [False, False, False, False, False],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [True, False, False, True, True],
         [False, True, True, False, True],
         [False, False, False, False, False],
    ],
    # 0b10000010:
    [
         [False, False, False, True, False],
         [False, False, True, False, False],
         [False, True, True, True, False],
         [True, False, False, False, True],
         [True, True, True, True, True],
         [True, False, False, False, False],
         [False, True, True, True, False],
         [False, False, False, False, False],
    ],
    # 0b10000011:
    [
         [False, False, True, False, False],
         [False, True, False, True, False],
         [False, True, True, True, False],
         [False, False, False, False, True],
         [False, True, True, True, True],
         [True, False, False, False, True],
         [False, True, True, True, True],
         [False, False, False, False, False],
    ],
    # 0b10000100:
    [
         [False, True, False, True, False],
         [False, False, False, False, False],
         [False, True, True, True, False],
         [False, False, False, False, True],
         [False, True, True, True, True],
         [True, False, False, False, True],
         [False, True, True, True, True],
         [False, False, False, False, False],
    ],
    # 0b10000101:
    [
         [False, True, False, False, False],
         [False, False, True, False, False],
         [False, True, True, True, False],
         [False, False, False, False, True],
         [False, True, True, True, True],
         [True, False, False, False, True],
         [False, True, True, True, True],
         [False, False, False, False, False],
    ],
    # 0b10000110:
    [
         [False, False, True, False, False],
         [False, False, False, False, False],
         [False, True, True, True, False],
         [False, False, False, False, True],
         [False, True, True, True, True],
         [True, False, False, False, True],
         [False, True, True, True, True],
         [False, False, False, False, False],
    ],
    # 0b10000111:
    [
         [False, False, False, False, False],
         [False, True, True, True, True],
         [True, False, False, False, False],
         [True, False, False, False, False],
         [False, True, True, True, True],
         [False, False, False, True, False],
         [False, True, True, True, False],
         [False, False, False, False, False],
    ],
    # 0b10001000:
    [
         [False, False, True, False, False],
         [False, True, False, True, False],
         [False, True, True, True, False],
         [True, False, False, False, True],
         [True, True, True, True, True],
         [True, False, False, False, False],
         [False, True, True, True, False],
         [False, False, False, False, False],
    ],
    # 0b10001001:
    [
         [False, True, False, True, False],
         [False, False, False, False, False],
         [False, True, True, True, False],
         [True, False, False, False, True],
         [True, True, True, True, True],
         [True, False, False, False, False],
         [False, True, True, True, False],
         [False, False, False, False, False],
    ],
    # 0b10001010:
    [
         [False, True, False, False, False],
         [False, False, True, False, False],
         [False, True, True, True, False],
         [True, False, False, False, True],
         [True, True, True, True, True],
         [True, False, False, False, False],
         [False, True, True, True, False],
         [False, False, False, False, False],
    ],
    # 0b10001011:
    [
         [False, True, False, True, False],
         [False, False, False, False, False],
         [False, True, True, False, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, True, True, True, False],
         [False, False, False, False, False],
    ],
    # 0b10001100:
    [
         [False, False, True, False, False],
         [False, True, False, True, False],
         [False, False, False, False, False],
         [False, True, True, False, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, True, True, True, False],
         [False, False, False, False, False],
    ],
    # 0b10001101:
    [
         [False, True, False, False, False],
         [False, False, True, False, False],
         [False, False, False, False, False],
         [False, True, True, False, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, True, True, True, False],
         [False, False, False, False, False],
    ],
    # 0b10001110:
    [
         [False, True, False, True, False],
         [False, False, False, False, False],
         [False, False, True, False, False],
         [False, True, False, True, False],
         [True, False, False, False, True],
         [True, True, True, True, True],
         [True, False, False, False, True],
         [False, False, False, False, False],
    ],
    # 0b10001111:
    [
         [False, False, True, False, False],
         [False, True, False, True, False],
         [False, False, True, False, False],
         [False, True, True, True, False],
         [True, False, False, False, True],
         [True, True, True, True, True],
         [True, False, False, False, True],
         [False, False, False, False, False],
    ],
    # 0b10010000:
    [
         [False, False, False, True, False],
         [False, False, True, False, False],
         [True, True, True, True, True],
         [True, False, False, False, False],
         [True, True, True, True, False],
         [True, False, False, False, False],
         [True, True, True, True, True],
         [False, False, False, False, False],
    ],
    # 0b10010001:
    [
         [False, False, False, False, False],
         [False, False, False, False, False],
         [True, True, False, True, False],
         [False, False, True, False, True],
         [False, True, True, True, True],
         [True, False, True, False, False],
         [False, True, True, True, True],
         [False, False, False, False, False],
    ],
    # 0b10010010:
    [
         [False, True, True, True, True],
         [True, False, True, False, False],
         [True, False, True, False, False],
         [True, True, True, True, True],
         [True, False, True, False, False],
         [True, False, True, False, False],
         [True, False, True, True, True],
         [False, False, False, False, False],
    ],
    # 0b10010011:
    [
         [False, False, True, False, False],
         [False, True, False, True, False],
         [False, False, False, False, False],
         [False, True, True, True, False],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [False, True, True, True, False],
         [False, False, False, False, False],
    ],
    # 0b10010100:
    [
         [False, False, False, False, False],
         [False, True, False, True, False],
         [False, False, False, False, False],
         [False, True, True, True, False],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [False, True, True, True, False],
         [False, False, False, False, False],
    ],
    # 0b10010101:
    [
         [False, True, False, False, False],
         [False, False, True, False, False],
         [False, False, False, False, False],
         [False, True, True, True, False],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [False, True, True, True, False],
         [False, False, False, False, False],
    ],
    # 0b10010110:
    [
         [False, False, True, False, False],
         [False, True, False, True, False],
         [False, False, False, False, False],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [True, False, False, True, True],
         [False, True, True, False, True],
         [False, False, False, False, False],
    ],
    # 0b10010111:
    [
         [False, True, False, False, False],
         [False, False, True, False, False],
         [False, False, False, False, False],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [True, False, False, True, True],
         [False, True, True, False, True],
         [False, False, False, False, False],
    ],
    # 0b10011000:
    [
         [False, True, False, True, False],
         [False, False, False, False, False],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [False, True, True, True, True],
         [False, False, False, False, True],
         [False, True, True, True, False],
         [False, False, False, False, False],
    ],
    # 0b10011001:
    [
         [True, False, False, False, True],
         [False, True, True, True, False],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [False, True, True, True, False],
         [False, False, False, False, False],
    ],
    # 0b10011010:
    [
         [False, True, False, True, False],
         [False, False, False, False, False],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [False, True, True, True, False],
         [False, False, False, False, False],
    ],
    # 0b10011011:
    [
         [False, True, True, False, True],
         [True, False, False, True, False],
         [False, False, False, False, False],
         [True, False, True, True, False],
         [True, True, False, False, True],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [False, False, False, False, False],
    ],
    # 0b10011100:
    [
         [False, True, True, False, True],
         [True, False, False, True, False],
         [False, False, False, False, False],
         [True, True, False, False, True],
         [True, False, True, False, True],
         [True, False, False, True, True],
         [True, False, False, False, True],
         [False, False, False, False, False],
    ],
    # 0b10011101:
    [
         [False, True, True, True, False],
         [False, False, False, False, True],
         [False, True, True, True, True],
         [True, False, False, False, True],
         [False, True, True, True, True],
         [False, False, False, False, False],
         [True, True, True, True, True],
         [False, False, False, False, False],
    ],
    # 0b10011110:
    [
         [False, True, True, True, False],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [False, True, True, True, False],
         [False, False, False, False, False],
         [True, True, True, True, True],
         [False, False, False, False, False],
    ],
    # 0b10011111:
    [
         [False, False, True, False, False],
         [False, False, False, False, False],
         [False, False, True, False, False],
         [False, True, False, False, False],
         [True, False, False, False, False],
         [True, False, False, False, True],
         [False, True, True, True, False],
         [False, False, False, False, False],
    ],
    # 0b10100000:
    [
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b10100001:
    [
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [True, True, True, False, False],
         [True, False, True, False, False],
         [True, True, True, False, False],
         [False, False, False, False, False],
    ],
    # 0b10100010:
    [
         [False, False, True, True, True],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b10100011:
    [
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [True, True, True, False, False],
         [False, False, False, False, False],
    ],
    # 0b10100100:
    [
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [True, False, False, False, False],
         [False, True, False, False, False],
         [False, False, True, False, False],
         [False, False, False, False, False],
    ],
    # 0b10100101:
    [
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, True, True, False, False],
         [False, True, True, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b10100110:
    [
         [False, False, False, False, False],
         [True, True, True, True, True],
         [False, False, False, False, True],
         [True, True, True, True, True],
         [False, False, False, False, True],
         [False, False, False, True, False],
         [False, False, True, False, False],
         [False, False, False, False, False],
    ],
    # 0b10100111:
    [
         [False, False, False, False, False],
         [False, False, False, False, False],
         [True, True, True, True, True],
         [False, False, False, False, True],
         [False, False, True, True, False],
         [False, False, True, False, False],
         [False, True, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b10101000:
    [
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, True, False],
         [False, False, True, False, False],
         [False, True, True, False, False],
         [True, False, True, False, False],
         [False, False, True, False, False],
         [False, False, False, False, False],
    ],
    # 0b10101001:
    [
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, True, False, False],
         [True, True, True, True, True],
         [True, False, False, False, True],
         [False, False, False, False, True],
         [False, False, True, True, False],
         [False, False, False, False, False],
    ],
    # 0b10101010:
    [
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [True, True, True, True, True],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [True, True, True, True, True],
         [False, False, False, False, False],
    ],
    # 0b10101011:
    [
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, True, False],
         [True, True, True, True, True],
         [False, False, True, True, False],
         [False, True, False, True, False],
         [True, False, False, True, False],
         [False, False, False, False, False],
    ],
    # 0b10101100:
    [
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, True, False, False, False],
         [True, True, True, True, True],
         [False, True, False, False, True],
         [False, True, False, True, False],
         [False, True, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b10101101:
    [
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, True, True, True, False],
         [False, False, False, True, False],
         [False, False, False, True, False],
         [True, True, True, True, True],
         [False, False, False, False, False],
    ],
    # 0b10101110:
    [
         [False, False, False, False, False],
         [False, False, False, False, False],
         [True, True, True, True, False],
         [False, False, False, True, False],
         [True, True, True, True, False],
         [False, False, False, True, False],
         [True, True, True, True, False],
         [False, False, False, False, False],
    ],
    # 0b10101111:
    [
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [True, False, True, False, True],
         [True, False, True, False, True],
         [False, False, False, False, True],
         [False, False, True, True, False],
         [False, False, False, False, False],
    ],
    # 0b10110000:
    [
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [True, True, True, True, True],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b10110001:
    [
         [True, True, True, True, True],
         [False, False, False, False, True],
         [False, False, True, False, True],
         [False, False, True, True, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, True, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b10110010:
    [
         [False, False, False, False, True],
         [False, False, False, True, False],
         [False, False, True, False, False],
         [False, True, True, False, False],
         [True, False, True, False, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, False, False, False],
    ],
    # 0b10110011:
    [
         [False, False, True, False, False],
         [True, True, True, True, True],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [False, False, False, False, True],
         [False, False, False, True, False],
         [False, False, True, False, False],
         [False, False, False, False, False],
    ],
    # 0b10110100:
    [
         [False, False, False, False, False],
         [True, True, True, True, True],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [True, True, True, True, True],
         [False, False, False, False, False],
    ],
    # 0b10110101:
    [
         [False, False, False, True, False],
         [True, True, True, True, True],
         [False, False, False, True, False],
         [False, False, True, True, False],
         [False, True, False, True, False],
         [True, False, False, True, False],
         [False, False, False, True, False],
         [False, False, False, False, False],
    ],
    # 0b10110110:
    [
         [False, True, False, False, False],
         [True, True, True, True, True],
         [False, True, False, False, True],
         [False, True, False, False, True],
         [False, True, False, False, True],
         [False, True, False, False, True],
         [True, False, False, True, False],
         [False, False, False, False, False],
    ],
    # 0b10110111:
    [
         [False, False, True, False, False],
         [True, True, True, True, True],
         [False, False, True, False, False],
         [True, True, True, True, True],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, False, False, False],
    ],
    # 0b10111000:
    [
         [False, False, False, False, False],
         [False, True, True, True, True],
         [False, True, False, False, True],
         [True, False, False, False, True],
         [False, False, False, False, True],
         [False, False, False, True, False],
         [False, True, True, False, False],
         [False, False, False, False, False],
    ],
    # 0b10111001:
    [
         [False, True, False, False, False],
         [False, True, True, True, True],
         [True, False, False, True, False],
         [False, False, False, True, False],
         [False, False, False, True, False],
         [False, False, False, True, False],
         [False, False, True, False, False],
         [False, False, False, False, False],
    ],
    # 0b10111010:
    [
         [False, False, False, False, False],
         [True, True, True, True, True],
         [False, False, False, False, True],
         [False, False, False, False, True],
         [False, False, False, False, True],
         [False, False, False, False, True],
         [True, True, True, True, True],
         [False, False, False, False, False],
    ],
    # 0b10111011:
    [
         [False, True, False, True, False],
         [True, True, True, True, True],
         [False, True, False, True, False],
         [False, True, False, True, False],
         [False, False, False, True, False],
         [False, False, True, False, False],
         [False, True, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b10111100:
    [
         [False, False, False, False, False],
         [True, True, False, False, False],
         [False, False, False, False, True],
         [True, True, False, False, True],
         [False, False, False, False, True],
         [False, False, False, True, False],
         [True, True, True, False, False],
         [False, False, False, False, False],
    ],
    # 0b10111101:
    [
         [False, False, False, False, False],
         [True, True, True, True, True],
         [False, False, False, False, True],
         [False, False, False, True, False],
         [False, False, True, False, False],
         [False, True, False, True, False],
         [True, False, False, False, True],
         [False, False, False, False, False],
    ],
    # 0b10111110:
    [
         [False, True, False, False, False],
         [True, True, True, True, True],
         [False, True, False, False, True],
         [False, True, False, True, False],
         [False, True, False, False, False],
         [False, True, False, False, False],
         [False, False, True, True, True],
         [False, False, False, False, False],
    ],
    # 0b10111111:
    [
         [False, False, False, False, False],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [False, True, False, False, True],
         [False, False, False, False, True],
         [False, False, False, True, False],
         [False, True, True, False, False],
         [False, False, False, False, False],
    ],
    # 0b11000000:
    [
         [False, False, False, False, False],
         [False, True, True, True, True],
         [False, True, False, False, True],
         [True, False, True, False, True],
         [False, False, False, True, True],
         [False, False, False, True, False],
         [False, True, True, False, False],
         [False, False, False, False, False],
    ],
    # 0b11000001:
    [
         [False, False, False, True, False],
         [True, True, True, False, False],
         [False, False, True, False, False],
         [True, True, True, True, True],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, True, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b11000010:
    [
         [False, False, False, False, False],
         [True, False, True, False, True],
         [True, False, True, False, True],
         [True, False, True, False, True],
         [False, False, False, False, True],
         [False, False, False, True, False],
         [False, False, True, False, False],
         [False, False, False, False, False],
    ],
    # 0b11000011:
    [
         [False, True, True, True, False],
         [False, False, False, False, False],
         [True, True, True, True, True],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, True, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b11000100:
    [
         [False, True, False, False, False],
         [False, True, False, False, False],
         [False, True, False, False, False],
         [False, True, True, False, False],
         [False, True, False, True, False],
         [False, True, False, False, False],
         [False, True, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b11000101:
    [
         [False, False, True, False, False],
         [False, False, True, False, False],
         [True, True, True, True, True],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, True, False, False, False],
         [True, False, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b11000110:
    [
         [False, False, False, False, False],
         [False, True, True, True, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [True, True, True, True, True],
         [False, False, False, False, False],
    ],
    # 0b11000111:
    [
         [False, False, False, False, False],
         [True, True, True, True, True],
         [False, False, False, False, True],
         [False, True, False, True, False],
         [False, False, True, False, False],
         [False, True, False, True, False],
         [True, False, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b11001000:
    [
         [False, False, True, False, False],
         [True, True, True, True, True],
         [False, False, False, True, False],
         [False, False, True, False, False],
         [False, True, True, True, False],
         [True, False, True, False, True],
         [False, False, True, False, False],
         [False, False, False, False, False],
    ],
    # 0b11001001:
    [
         [False, False, False, True, False],
         [False, False, False, True, False],
         [False, False, False, True, False],
         [False, False, False, True, False],
         [False, False, False, True, False],
         [False, False, True, False, False],
         [False, True, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b11001010:
    [
         [False, False, False, False, False],
         [False, False, True, False, False],
         [False, False, False, True, False],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [False, False, False, False, False],
    ],
    # 0b11001011:
    [
         [True, False, False, False, False],
         [True, False, False, False, False],
         [True, True, True, True, True],
         [True, False, False, False, False],
         [True, False, False, False, False],
         [True, False, False, False, False],
         [False, True, True, True, True],
         [False, False, False, False, False],
    ],
    # 0b11001100:
    [
         [False, False, False, False, False],
         [True, True, True, True, True],
         [False, False, False, False, True],
         [False, False, False, False, True],
         [False, False, False, False, True],
         [False, False, False, True, False],
         [False, True, True, False, False],
         [False, False, False, False, False],
    ],
    # 0b11001101:
    [
         [False, False, False, False, False],
         [False, True, False, False, False],
         [True, False, True, False, False],
         [False, False, False, True, False],
         [False, False, False, False, True],
         [False, False, False, False, True],
         [False, False, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b11001110:
    [
         [False, False, True, False, False],
         [True, True, True, True, True],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [True, False, True, False, True],
         [True, False, True, False, True],
         [False, False, True, False, False],
         [False, False, False, False, False],
    ],
    # 0b11001111:
    [
         [False, False, False, False, False],
         [True, True, True, True, True],
         [False, False, False, False, True],
         [False, False, False, False, True],
         [False, True, False, True, False],
         [False, False, True, False, False],
         [False, False, False, True, False],
         [False, False, False, False, False],
    ],
    # 0b11010000:
    [
         [False, False, False, False, False],
         [False, True, True, True, False],
         [False, False, False, False, False],
         [False, True, True, True, False],
         [False, False, False, False, False],
         [False, True, True, True, False],
         [False, False, False, False, True],
         [False, False, False, False, False],
    ],
    # 0b11010001:
    [
         [False, False, False, False, False],
         [False, False, True, False, False],
         [False, True, False, False, False],
         [True, False, False, False, False],
         [True, False, False, False, True],
         [True, True, True, True, True],
         [False, False, False, False, True],
         [False, False, False, False, False],
    ],
    # 0b11010010:
    [
         [False, False, False, False, False],
         [False, False, False, False, True],
         [False, False, False, False, True],
         [False, True, False, True, False],
         [False, False, True, False, False],
         [False, True, False, True, False],
         [True, False, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b11010011:
    [
         [False, False, False, False, False],
         [True, True, True, True, True],
         [False, True, False, False, False],
         [True, True, True, True, True],
         [False, True, False, False, False],
         [False, True, False, False, False],
         [False, False, True, True, True],
         [False, False, False, False, False],
    ],
    # 0b11010100:
    [
         [False, True, False, False, False],
         [False, True, False, False, False],
         [True, True, True, True, True],
         [False, True, False, False, True],
         [False, True, False, True, False],
         [False, True, False, False, False],
         [False, True, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b11010101:
    [
         [False, False, False, False, False],
         [False, True, True, True, False],
         [False, False, False, True, False],
         [False, False, False, True, False],
         [False, False, False, True, False],
         [False, False, False, True, False],
         [True, True, True, True, True],
         [False, False, False, False, False],
    ],
    # 0b11010110:
    [
         [False, False, False, False, False],
         [True, True, True, True, True],
         [False, False, False, False, True],
         [True, True, True, True, True],
         [False, False, False, False, True],
         [False, False, False, False, True],
         [True, True, True, True, True],
         [False, False, False, False, False],
    ],
    # 0b11010111:
    [
         [False, True, True, True, False],
         [False, False, False, False, False],
         [True, True, True, True, True],
         [False, False, False, False, True],
         [False, False, False, False, True],
         [False, False, False, True, False],
         [False, False, True, False, False],
         [False, False, False, False, False],
    ],
    # 0b11011000:
    [
         [True, False, False, True, False],
         [True, False, False, True, False],
         [True, False, False, True, False],
         [True, False, False, True, False],
         [False, False, False, True, False],
         [False, False, True, False, False],
         [False, True, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b11011001:
    [
         [False, False, False, False, False],
         [False, False, True, False, False],
         [True, False, True, False, False],
         [True, False, True, False, False],
         [True, False, True, False, True],
         [True, False, True, False, True],
         [True, False, True, True, False],
         [False, False, False, False, False],
    ],
    # 0b11011010:
    [
         [False, False, False, False, False],
         [True, False, False, False, False],
         [True, False, False, False, False],
         [True, False, False, False, True],
         [True, False, False, True, False],
         [True, False, True, False, False],
         [True, True, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b11011011:
    [
         [False, False, False, False, False],
         [True, True, True, True, True],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [True, True, True, True, True],
         [False, False, False, False, False],
    ],
    # 0b11011100:
    [
         [False, False, False, False, False],
         [True, True, True, True, True],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [False, False, False, False, True],
         [False, False, False, True, False],
         [False, False, True, False, False],
         [False, False, False, False, False],
    ],
    # 0b11011101:
    [
         [False, False, False, False, False],
         [True, True, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, True],
         [False, False, False, False, True],
         [False, False, False, True, False],
         [True, True, True, False, False],
         [False, False, False, False, False],
    ],
    # 0b11011110:
    [
         [False, False, True, False, False],
         [True, False, False, True, False],
         [False, True, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b11011111:
    [
         [True, True, True, False, False],
         [True, False, True, False, False],
         [True, True, True, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b11100000:
    [
         [False, False, False, True, False],
         [False, False, True, False, False],
         [False, True, True, True, False],
         [False, False, False, False, True],
         [False, True, True, True, True],
         [True, False, False, False, True],
         [False, True, True, True, True],
         [False, False, False, False, False],
    ],
    # 0b11100001:
    [
         [False, False, False, True, False],
         [False, False, True, False, False],
         [False, False, False, False, False],
         [False, True, True, False, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, True, True, True, False],
         [False, False, False, False, False],
    ],
    # 0b11100010:
    [
         [False, False, False, True, False],
         [False, False, True, False, False],
         [False, False, False, False, False],
         [False, True, True, True, False],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [False, True, True, True, False],
         [False, False, False, False, False],
    ],
    # 0b11100011:
    [
         [False, False, False, True, False],
         [False, False, True, False, False],
         [False, False, False, False, False],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [True, False, False, True, True],
         [False, True, True, False, True],
         [False, False, False, False, False],
    ],
    # 0b11100100:
    [
         [False, False, True, False, False],
         [False, True, True, True, True],
         [True, False, True, False, False],
         [True, False, True, False, False],
         [True, False, True, False, False],
         [False, True, True, True, True],
         [False, False, True, False, False],
         [False, False, False, False, False],
    ],
    # 0b11100101:
    [
         [False, False, True, True, False],
         [False, True, False, False, True],
         [False, True, False, False, False],
         [True, True, True, True, False],
         [False, True, False, False, False],
         [False, True, False, False, False],
         [True, True, True, True, True],
         [False, False, False, False, False],
    ],
    # 0b11100110:
    [
         [True, False, False, False, True],
         [False, True, False, True, False],
         [True, True, True, True, True],
         [False, False, True, False, False],
         [True, True, True, True, True],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, False, False, False],
    ],
    # 0b11100111:
    [
         [True, True, True, False, False],
         [True, False, False, True, False],
         [True, True, True, False, False],
         [True, False, False, True, False],
         [True, False, True, True, True],
         [True, False, False, True, False],
         [True, False, False, True, True],
         [False, False, False, False, False],
    ],
    # 0b11101000:
    [
         [False, False, False, True, False],
         [False, False, True, False, True],
         [False, False, True, False, False],
         [False, True, True, True, False],
         [False, False, True, False, False],
         [True, False, True, False, False],
         [False, True, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b11101001:
    [
         [False, False, True, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, False, False, False],
    ],
    # 0b11101010:
    [
         [False, True, True, False, True],
         [True, False, False, True, False],
         [False, False, False, False, False],
         [False, True, True, True, False],
         [True, False, False, False, True],
         [True, True, True, True, True],
         [True, False, False, False, True],
         [False, False, False, False, False],
    ],
    # 0b11101011:
    [
         [False, True, True, False, True],
         [True, False, False, True, False],
         [False, False, True, True, False],
         [False, False, False, False, True],
         [False, True, True, True, True],
         [True, False, False, False, True],
         [False, True, True, True, True],
         [False, False, False, False, False],
    ],
    # 0b11101100:
    [
         [False, True, True, False, True],
         [True, False, False, True, False],
         [False, True, True, True, False],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [False, True, True, True, False],
         [False, False, False, False, False],
    ],
    # 0b11101101:
    [
         [False, True, True, False, True],
         [True, False, False, True, False],
         [False, False, False, False, False],
         [False, True, True, True, False],
         [True, False, False, False, True],
         [True, False, False, False, True],
         [False, True, True, True, False],
         [False, False, False, False, False],
    ],
    # 0b11101110:
    [
         [False, False, False, False, True],
         [False, True, True, True, False],
         [True, False, False, True, True],
         [True, False, True, False, True],
         [True, True, False, False, True],
         [False, True, True, True, False],
         [True, False, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b11101111:
    [
         [False, False, False, False, False],
         [False, False, False, True, False],
         [False, True, True, True, False],
         [True, False, True, False, True],
         [True, False, True, False, True],
         [False, True, True, True, False],
         [False, True, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b11110000:
    [
         [False, False, True, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b11110001:
    [
         [False, True, False, True, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b11110010:
    [
         [False, False, True, False, False],
         [False, True, False, True, False],
         [False, False, True, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b11110011:
    [
         [False, True, False, False, False],
         [False, False, True, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b11110100:
    [
         [False, False, False, True, False],
         [False, False, True, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b11110101:
    [
         [True, False, False, False, False],
         [True, False, False, False, False],
         [True, False, False, True, False],
         [True, False, True, False, True],
         [False, False, False, False, True],
         [False, False, False, True, False],
         [False, False, True, True, True],
         [False, False, False, False, False],
    ],
    # 0b11110110:
    [
         [True, False, False, False, False],
         [True, False, False, False, False],
         [True, False, True, False, False],
         [True, False, True, False, True],
         [False, False, True, False, True],
         [False, False, True, True, True],
         [False, False, False, False, True],
         [False, False, False, False, False],
    ],
    # 0b11110111:
    [
         [False, False, False, False, False],
         [True, False, False, False, True],
         [False, True, False, True, False],
         [False, False, True, False, False],
         [False, True, False, True, False],
         [True, False, False, False, True],
         [False, False, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b11111000:
    [
         [False, False, False, False, False],
         [False, False, True, False, False],
         [False, False, False, False, False],
         [True, True, True, True, True],
         [False, False, False, False, False],
         [False, False, True, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b11111001:
    [
         [False, False, False, True, False],
         [False, False, True, False, False],
         [False, True, False, False, False],
         [False, False, True, False, False],
         [False, False, False, True, False],
         [False, False, False, False, False],
         [True, True, True, True, True],
         [False, False, False, False, False],
    ],
    # 0b11111010:
    [
         [False, True, False, False, False],
         [False, False, True, False, False],
         [False, False, False, True, False],
         [False, False, True, False, False],
         [False, True, False, False, False],
         [False, False, False, False, False],
         [True, True, True, True, True],
         [False, False, False, False, False],
    ],
    # 0b11111011:
    [
         [False, False, False, False, False],
         [False, False, True, False, True],
         [False, True, False, True, False],
         [True, False, True, False, False],
         [False, True, False, True, False],
         [False, False, True, False, True],
         [False, False, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b11111100:
    [
         [False, False, False, False, False],
         [True, False, True, False, False],
         [False, True, False, True, False],
         [False, False, True, False, True],
         [False, True, False, True, False],
         [True, False, True, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b11111101:
    [
         [False, False, False, True, False],
         [False, False, False, True, False],
         [True, True, True, True, True],
         [False, False, True, False, False],
         [True, True, True, True, True],
         [False, True, False, False, False],
         [False, True, False, False, False],
         [False, False, False, False, False],
    ],
    # 0b11111110:
    [
         [False, False, True, True, True],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [False, False, True, False, False],
         [True, False, True, False, False],
         [False, True, True, False, False],
         [False, False, True, False, False],
         [False, False, False, False, False],
    ],
    # 0b11111111:
    [
         [True, True, True, True, True],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
    ],
]
